language: node_js
node_js:
    - "0.10"
services:
    - xvfb
    - postgresql
before_install:
    - export DISPLAY=:99.0
before_script:
    - bundle install
    - npm install karma
script:
    - node_modules/karma/bin/karma start my.conf.js --single-run
    - bundle exec rspec
